### PR TITLE
[lang] escaped apostrophes in string literals are optional

### PR DESCRIPTION
**Pull request by srackham**
See #87.

### CODE REVIEW

**Review by titzer — CHANGES_REQUESTED** [review]
lgtm. Can you add a couple of tests to `test/core/` as well? E.g. a few parser tests and an execution test that verifies the values of characters parsed?

Also, please run `aeneas bump`, as this change, though it's in the library and I normally wouldn't bump the version just for the library, does affect the language.

**Review by srackham — COMMENTED** [review]
I assumed the doubled up `var j` was a typo and bumped it to `var k`.

**Comment by titzer** [comment]
Thanks! lgtm.

**Comment by srackham** [comment]
My pleasure, PRs are a great way to learn.

**Pull request merged**
